name: login2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^2.0.0
  fluttertoast: ^8.0.8
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  http: ^0.13.3
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^10.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
# here im telling flutter that there are images inside assets and inside assets.icons
  assets:
    - assets/
    - assets/icons/