name: login2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  cached_network_image: ^3.0.0
  timeago: ^3.0.2
  video_player: ^2.3.0  # Corrected to latest version
  animate_do: ^3.3.4
  shimmer: ^3.0.0
  flutter_sound: ^9.6.0
  permission_handler: ^11.3.1
  fluttertoast: ^8.0.8
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  http: ^1.2.2
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^11.0.0
  shared_preferences: ^2.0.6
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
